name: Deploy to Docker Hub and Server (Staging)

on:
  push:
    branches:
      - dev
  workflow_dispatch: 

jobs:
  deploy-to-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image for staging
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: rifkinauvaldzaki/movie-academy:staging
          build-args: |
            ENVIRONMENT=staging
            PORT=3001

      - name: Deploy to Staging Container
        env:
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        run: |
          sshpass -p "${SERVER_PASSWORD}" ssh -o StrictHostKeyChecking=no technova@103.142.21.43 "
            docker stop movie-academy-staging-container || true &&
            docker rm movie-academy-staging-container || true &&
            docker pull rifkinauvaldzaki/movie-academy:staging &&

            # Delete <none> tags
            docker image prune -f &&

            docker run -d --name movie-academy-staging-container -p 3001:3001 -e ENVIRONMENT=staging -e PORT=3001 rifkinauvaldzaki/movie-academy:staging
          "
