name: Deploy to Docker Hub and Server (Production)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-to-production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image for production
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: rifkinauvaldzaki/movie-academy:latest
          build-args: |
            ENVIRONMENT=production
            PORT=3002

      - name: Deploy to Production Container
        env:
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        run: |
          sshpass -p "${SERVER_PASSWORD}" ssh -o StrictHostKeyChecking=no technova@103.142.21.43 "
            docker stop movie-academy-production-container || true &&
            docker rm movie-academy-production-container || true &&
            docker pull rifkinauvaldzaki/movie-academy:latest &&

            # Delete <none> tags
            docker image prune -f &&

            docker run -d --name movie-academy-production-container -p 3002:3002 -e ENVIRONMENT=production -e PORT=3002 rifkinauvaldzaki/movie-academy:latest
          "
